/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ServiceRequestsRouteImport } from './routes/service-requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerWorkOrdersRouteImport } from './routes/customer.work-orders'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as TechnicianDashboardRouteImport } from './routes/technician.dashboard'
import { Route as TechnicianJobsRouteImport } from './routes/technician.jobs'
import { Route as TechniciansIdRouteImport } from './routes/technicians.$id'
import { Route as WorkOrdersIdRouteImport } from './routes/work-orders.$id'
import { Route as TechnicianJobsIdRouteImport } from './routes/technician.jobs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsRoute = ServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/customer/requests',
  path: '/customer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWorkOrdersRoute = CustomerWorkOrdersRouteImport.update({
  id: '/customer/work-orders',
  path: '/customer/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const TechnicianDashboardRoute = TechnicianDashboardRouteImport.update({
  id: '/technician/dashboard',
  path: '/technician/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianJobsRoute = TechnicianJobsRouteImport.update({
  id: '/technician/jobs',
  path: '/technician/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIdRoute = TechniciansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TechniciansRoute,
} as any)
const WorkOrdersIdRoute = WorkOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const TechnicianJobsIdRoute = TechnicianJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TechnicianJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/service-requests': typeof ServiceRequestsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/work-orders': typeof CustomerWorkOrdersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRouteWithChildren
  '/technicians/$id': typeof TechniciansIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/technician/jobs/$id': typeof TechnicianJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/service-requests': typeof ServiceRequestsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/work-orders': typeof CustomerWorkOrdersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRouteWithChildren
  '/technicians/$id': typeof TechniciansIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/technician/jobs/$id': typeof TechnicianJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/service-requests': typeof ServiceRequestsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/work-orders': typeof CustomerWorkOrdersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/jobs': typeof TechnicianJobsRouteWithChildren
  '/technicians/$id': typeof TechniciansIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/technician/jobs/$id': typeof TechnicianJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/schedule'
    | '/service-requests'
    | '/settings'
    | '/sla'
    | '/technicians'
    | '/work-orders'
    | '/assets/$id'
    | '/customer/dashboard'
    | '/customer/requests'
    | '/customer/work-orders'
    | '/customers/$id'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/technicians/$id'
    | '/work-orders/$id'
    | '/technician/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/schedule'
    | '/service-requests'
    | '/settings'
    | '/sla'
    | '/technicians'
    | '/work-orders'
    | '/assets/$id'
    | '/customer/dashboard'
    | '/customer/requests'
    | '/customer/work-orders'
    | '/customers/$id'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/technicians/$id'
    | '/work-orders/$id'
    | '/technician/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/schedule'
    | '/service-requests'
    | '/settings'
    | '/sla'
    | '/technicians'
    | '/work-orders'
    | '/assets/$id'
    | '/customer/dashboard'
    | '/customer/requests'
    | '/customer/work-orders'
    | '/customers/$id'
    | '/technician/dashboard'
    | '/technician/jobs'
    | '/technicians/$id'
    | '/work-orders/$id'
    | '/technician/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  ServiceRequestsRoute: typeof ServiceRequestsRoute
  SettingsRoute: typeof SettingsRoute
  SlaRoute: typeof SlaRoute
  TechniciansRoute: typeof TechniciansRouteWithChildren
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerRequestsRoute: typeof CustomerRequestsRoute
  CustomerWorkOrdersRoute: typeof CustomerWorkOrdersRoute
  TechnicianDashboardRoute: typeof TechnicianDashboardRoute
  TechnicianJobsRoute: typeof TechnicianJobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests': {
      id: '/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof ServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/customer/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/work-orders': {
      id: '/customer/work-orders'
      path: '/customer/work-orders'
      fullPath: '/customer/work-orders'
      preLoaderRoute: typeof CustomerWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/technician/dashboard': {
      id: '/technician/dashboard'
      path: '/technician/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof TechnicianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/jobs': {
      id: '/technician/jobs'
      path: '/technician/jobs'
      fullPath: '/technician/jobs'
      preLoaderRoute: typeof TechnicianJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/$id': {
      id: '/technicians/$id'
      path: '/$id'
      fullPath: '/technicians/$id'
      preLoaderRoute: typeof TechniciansIdRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/work-orders/$id': {
      id: '/work-orders/$id'
      path: '/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof WorkOrdersIdRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/technician/jobs/$id': {
      id: '/technician/jobs/$id'
      path: '/$id'
      fullPath: '/technician/jobs/$id'
      preLoaderRoute: typeof TechnicianJobsIdRouteImport
      parentRoute: typeof TechnicianJobsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface TechniciansRouteChildren {
  TechniciansIdRoute: typeof TechniciansIdRoute
}

const TechniciansRouteChildren: TechniciansRouteChildren = {
  TechniciansIdRoute: TechniciansIdRoute,
}

const TechniciansRouteWithChildren = TechniciansRoute._addFileChildren(
  TechniciansRouteChildren,
)

interface WorkOrdersRouteChildren {
  WorkOrdersIdRoute: typeof WorkOrdersIdRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersIdRoute: WorkOrdersIdRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

interface TechnicianJobsRouteChildren {
  TechnicianJobsIdRoute: typeof TechnicianJobsIdRoute
}

const TechnicianJobsRouteChildren: TechnicianJobsRouteChildren = {
  TechnicianJobsIdRoute: TechnicianJobsIdRoute,
}

const TechnicianJobsRouteWithChildren = TechnicianJobsRoute._addFileChildren(
  TechnicianJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  ServiceRequestsRoute: ServiceRequestsRoute,
  SettingsRoute: SettingsRoute,
  SlaRoute: SlaRoute,
  TechniciansRoute: TechniciansRouteWithChildren,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerRequestsRoute: CustomerRequestsRoute,
  CustomerWorkOrdersRoute: CustomerWorkOrdersRoute,
  TechnicianDashboardRoute: TechnicianDashboardRoute,
  TechnicianJobsRoute: TechnicianJobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
