import type { ReactNode } from "react";
import { ArrowDownRight, ArrowUpRight, Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description:string;actions?:ReactNode}){return <header className="flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0">{eyebrow&&<p className="mb-2 text-[11px] font-semibold uppercase tracking-[.14em] text-primary">{eyebrow}</p>}<h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h1><p className="mt-1.5 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{actions&&<div className="max-w-full shrink-0">{actions}</div>}</header>}
export function Metric({label,value,context,tone="default"}:{label:string;value:string;context:string;tone?:"default"|"warning"|"critical"}){return <div className="group border-l border-border px-4 first:border-l-0 first:pl-0 sm:px-5"><div className="flex items-start justify-between gap-2"><p className={cn("font-mono text-2xl font-medium tabular-nums sm:text-3xl",tone==="warning"&&"text-warning",tone==="critical"&&"text-critical")}>{value}</p><ArrowUpRight className="mt-1 h-3.5 w-3.5 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></div><p className="mt-2 text-xs font-medium text-foreground">{label}</p><p className="mt-1 text-[11px] text-muted-foreground">{context}</p></div>}
export function Panel({title,description,action,children,className}:{title?:string;description?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={cn("panel rounded-lg",className)}>{(title||action)&&<div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border px-4 py-3.5"><div className="min-w-0">{title&&<h2 className="truncate text-sm font-medium">{title}</h2>}{description&&<p className="mt-0.5 truncate text-xs text-muted-foreground">{description}</p>}</div>{action}</div>}{children}</section>}
export function EmptyState({title="Nothing here yet",description="New activity will appear here when it arrives."}:{title?:string;description?:string}){return <div className="grid min-h-48 place-items-center p-8 text-center"><div><span className="mx-auto grid h-9 w-9 place-items-center rounded-md border border-border bg-surface-2 text-muted-foreground"><Inbox className="h-4 w-4"/></span><h3 className="mt-3 text-sm font-medium">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{description}</p><Button variant="quiet" size="sm" className="mt-4">Refresh <ArrowDownRight/></Button></div></div>}
export function SectionTabs({items,active,onChange}:{items:string[];active:string;onChange:(v:string)=>void}){return <div className="inline-flex rounded-md border border-border bg-surface-1 p-0.5">{items.map(i=><Button key={i} size="sm" variant={active===i?"secondary":"ghost"} onClick={()=>onChange(i)} className="h-7 px-2.5 text-[11px]">{i}</Button>)}</div>}
